language: node_js
node_js:
  - "7"

before_script:
  - npm prune
install: npm install

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_API_KEY
  on:
    tags: true

notifications:
  email:
    recipients:
      - $NPM_EMAIL
    on_success: change
    on_failure: always

